name: Docker build
description: Builds a Docker image for this application
inputs:
    docker-username:
        description: The username of the Docker user
        required: true
    docker-password:
        description: The password of the Docker user
        required: true
    docker-image-name:
        description: The name of the Docker image
        required: true
    docker-image-tags:
        description: The tags to set on the Docker image
        default: latest
runs:
    using: composite
    steps:
        - name: Login to Docker Hub
          uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
          with:
              username: ${{ inputs.docker-username }}
              password: ${{ inputs.docker-password }}

        - name: Login to dhi.io
          uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
          with:
              registry: dhi.io
              username: ${{ inputs.docker-username }}
              password: ${{ inputs.docker-password }}

        - name: Set up docker Buildx
          uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

        - name: Extract metadata
          id: docker-metadata
          uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
          with:
              images: ${{ inputs.docker-image-name }}

        - name: Build Docker image
          uses: docker/bake-action@5be5f02ff8819ecd3092ea6b2e6261c31774f2b4 # v6.10.0
          env:
              TAGS: ${{ inputs.docker-image-tags }}
          with:
              source: .
              push: true
              files: |
                  .docker/docker-bake.hcl
                  cwd://${{ steps.docker-metadata.outputs.bake-file }}

        - name: Update Docker Hub description
          uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
          with:
              username: ${{ inputs.docker-username }}
              password: ${{ inputs.docker-password }}
              repository: dndmapp/template-angular-app
              short-description: ${{ github.event.repository.description }}
              readme-filepath: .docker/README.md
              enable-url-completion: true
