# syntax=docker/dockerfile:1
# check=error=true

FROM --platform=$BUILDPLATFORM dhi.io/node:24.12.0-dev AS build

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

ENV NODE_ENV=production

COPY . .

RUN pnpm run build


FROM dhi.io/nginx:1.29.4-alpine3.21

WORKDIR /usr/share/nginx/html

COPY --from=build /app/dist/template-angular-app/browser .

COPY .docker/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

CMD ["-g", "daemon off;"]
