name: Set up tools
description: Set up repository Tools (Node.js and pnpm)
inputs:
    install-dependencies:
        description: Whether to install dependencies
        required: false
        default: 'true'
runs:
    using: composite
    steps:
        - name: Setup Pnpm
          uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

        - name: Setup Node.js
          uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
          with:
              cache: pnpm
              cache-dependency-path: pnpm-lock.yaml
              node-version-file: .tool-versions

        - name: Install dependencies
          if: ${{ inputs.install-dependencies == 'true' }}
          shell: bash
          run: pnpm install --frozen-lockfile
